### ISSUE TITLE
Typo in <Title> Tag

### ISSUE THREAD

**Issue by reposited** [reposited/linktree-webpage#1]
There's a small typo in the <title> tag.
(Doesn't match domain name)

This issue will be resolved in the next commitment.

**Comment by Osiris34** [comment]
May I fix this issue?

**Comment by reposited** [comment]
> May I fix this issue?

@Osiris34 Yes you may, if you would like my contacts as well they are on my page and about-me repo. Thank you :)

**Comment by reposited** [comment]
# Reason for Issue reopening: 
_Waited for user @Osiris34 to paste a pull request. This issue has been reopened_ 

The issue is now Resolved ☑

**Comment by reposited** [comment]
# Reason for Issue reopening: 
_Waited for user @Osiris34 to paste a pull request. This issue has been reopened_ 

The issue is now Resolved ☑
